version: '3.3'
services:
  triton:
    image: 6e61746566616e61726f/triton:latest
    command: bash -c "CUDA_VISIBLE_DEVICES=${GPUS} mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver --model-repository=/model"
    shm_size: '2gb'
    volumes:
      - ${MODEL_DIR}:/model
      - ${HF_CACHE_DIR}:/root/.cache/huggingface
    ports:
      - "8000:8000"
      - "${TRITON_PORT}:8001"
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  copilot_proxy:
    image: 6e61746566616e61726f/copilot_proxy:latest
    env_file:
      - .env
    ports:
      - "${API_EXTERNAL_PORT}:5000"
